const floorImages={ground:'assets/floor_ground.svg',upper:'assets/floor_upper.svg'};
let tags=JSON.parse(localStorage.getItem('homeTrackTags')||'null')||[
{id:'F01',name:'Ba',type:'family',floor:'ground',zone:'Phòng khách',x:28,y:72,battery:82,status:'online',last:'Vừa xong'},{id:'F02',name:'Mẹ',type:'family',floor:'ground',zone:'Bếp',x:78,y:25,battery:64,status:'online',last:'1 phút trước'},{id:'F03',name:'Minh',type:'family',floor:'upper',zone:'Phòng ngủ lớn',x:28,y:66,battery:18,status:'online',last:'Vừa xong'},{id:'F04',name:'Phương',type:'family',floor:'upper',zone:'Phòng nhỏ',x:77,y:73,battery:73,status:'online',last:'2 phút trước'},{id:'F05',name:'Ông',type:'family',floor:'ground',zone:'Phòng đàn',x:39,y:27,battery:91,status:'online',last:'3 phút trước'},{id:'F06',name:'Bà',type:'family',floor:'upper',zone:'Hành lang',x:55,y:65,battery:55,status:'offline',last:'18 phút trước'},{id:'G01',name:'Cô Lan',type:'guest',floor:'ground',zone:'Phòng ăn',x:78,y:73,battery:42,status:'online',last:'Vừa xong'},{id:'G02',name:'Chú Hùng',type:'guest',floor:'ground',zone:'Gara',x:12,y:28,battery:15,status:'online',last:'4 phút trước'},{id:'G03',name:'Khách 03',type:'guest',floor:'upper',zone:'Phòng ngủ lớn',x:25,y:35,battery:69,status:'online',last:'6 phút trước'},{id:'G04',name:'Chưa giao',type:'guest',floor:'ground',zone:'Giá thẻ',x:48,y:84,battery:100,status:'offline',last:'Đã trả'},{id:'G05',name:'Chưa giao',type:'guest',floor:'ground',zone:'Giá thẻ',x:51,y:84,battery:96,status:'offline',last:'Đã trả'},{id:'G06',name:'Chưa giao',type:'guest',floor:'ground',zone:'Giá thẻ',x:54,y:84,battery:88,status:'offline',last:'Đã trả'}];
let currentFloor='ground',selectedId=null;const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const titles={dashboard:['Tổng quan','Theo dõi trạng thái thẻ và khu vực trong nhà'],locator:['Định vị trong nhà','Mô phỏng vị trí thẻ trên sơ đồ hai tầng'],tags:['Quản lý thẻ','Theo dõi pin, trạng thái và phân công thẻ'],alerts:['Cảnh báo','Các sự cố cần xử lý trong hệ thống'],settings:['Cài đặt','Quyền riêng tư và thông báo hệ thống']};
function save(){localStorage.setItem('homeTrackTags',JSON.stringify(tags))}function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}window.showToast=toast;
function switchView(v){$$('.view').forEach(x=>x.classList.remove('active'));$('#'+v+'View').classList.add('active');$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#pageTitle').textContent=titles[v][0];$('#pageSubtitle').textContent=titles[v][1];if(v==='locator')renderMap()}$$('.nav-btn').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>switchView(b.dataset.jump));
function zone(f,x,y){if(f==='ground'){if(x<24&&y<55)return'Gara';if(x<56&&y<55)return'Phòng đàn';if(x>70&&y<55)return'Bếp';if(x<56)return'Phòng khách';if(x>70)return'Phòng ăn';return'Sảnh'}if(x<43&&y<30)return'Nhà vệ sinh';if(x<43)return'Phòng ngủ lớn';if(x>68&&y<52)return'Phòng ngủ chính';if(x>68)return'Phòng sinh hoạt';return'Hành lang'}
function renderStats(){$('#onlineCount').textContent=tags.filter(t=>t.status==='online').length;$('#guestCount').textContent=tags.filter(t=>t.type==='guest'&&t.name!=='Chưa giao').length;$('#lowBatteryCount').textContent=tags.filter(t=>t.battery<20).length}
function renderMini(){const r=$('#miniMarkers');r.innerHTML='';tags.filter(t=>t.floor==='ground'&&t.status==='online'&&t.zone!=='Giá thẻ').forEach(t=>{let e=document.createElement('div');e.className='mini-marker';e.style.cssText=`left:${t.x}%;top:${t.y}%;background:${t.type==='guest'?'#9b6bdb':'#4f7cff'}`;e.textContent=t.name[0];r.appendChild(e)})}
function renderAttention(){let a=[];tags.filter(t=>t.battery<20).forEach(t=>a.push([`${t.name} còn ${t.battery}% pin`,`Thẻ ${t.id} cần sạc sớm`]));tags.filter(t=>t.status==='offline'&&t.name!=='Chưa giao').forEach(t=>a.push([`Không thấy ${t.name}`,`Lần cuối: ${t.last}`]));$('#attentionList').innerHTML=a.map(x=>`<div class="attention"><div class="badge-icon">!</div><div><b>${x[0]}</b><small>${x[1]}</small></div></div>`).join('')||'<p>Không có cảnh báo.</p>';$('#timeline').innerHTML=['F01 chuyển đến Phòng khách','G01 được giao cho Cô Lan','Gateway tầng trên kết nối lại'].map((x,i)=>`<div class="timeline-item"><div class="badge-icon">•</div><div><b>${x}</b><small>${i*8+1} phút trước</small></div></div>`).join('')}
function detail(t){$('#detailPanel').innerHTML=`<div class="person-card"><span class="pill ${t.type}">${t.type==='family'?'Gia đình':'Khách'}</span><h3>${t.name}</h3><div class="sub">${t.id} · ${t.status==='online'?'Đang trực tuyến':'Ngoại tuyến'}</div><div class="detail-grid"><div class="detail-box"><span>Khu vực</span><b>${t.zone}</b></div><div class="detail-box"><span>Lần thấy cuối</span><b>${t.last}</b></div><div class="detail-box"><span>Pin</span><b>${t.battery}%</b><div class="battery"><i style="width:${t.battery}%;background:${t.battery<20?'#e66060':'#27b37e'}"></i></div></div><div class="detail-box"><span>Tầng</span><b>${t.floor==='ground'?'Tầng trệt':'Tầng trên'}</b></div></div><button class="primary" style="width:100%" onclick="showToast('Đã gửi lệnh phát còi cho ${t.id}')">Phát còi tìm thẻ</button></div>`}
function drag(e,t){let d=false;e.onpointerdown=x=>{d=true;e.setPointerCapture(x.pointerId)};e.onpointermove=x=>{if(!d)return;let r=$('#floorMap').getBoundingClientRect();t.x=Math.max(2,Math.min(98,(x.clientX-r.left)/r.width*100));t.y=Math.max(2,Math.min(98,(x.clientY-r.top)/r.height*100));e.style.left=t.x+'%';e.style.top=t.y+'%'};e.onpointerup=()=>{if(d){d=false;t.zone=zone(currentFloor,t.x,t.y);t.last='Vừa xong';save();detail(t);toast(`${t.name} đã chuyển đến ${t.zone}`)}}}
function renderMap(){$('#floorImage').src=floorImages[currentFloor];const l=$('#markerLayer');l.innerHTML='';let ty=$('#typeFilter').value,st=$('#statusFilter').value;tags.filter(t=>t.floor===currentFloor&&t.zone!=='Giá thẻ'&&(ty==='all'||t.type===ty)&&(st==='all'||t.status===st)).forEach(t=>{let e=document.createElement('div');e.className=`marker ${t.type} ${t.status}${selectedId===t.id?' selected':''}`;e.style.left=t.x+'%';e.style.top=t.y+'%';e.textContent=t.name.split(' ').map(w=>w[0]).join('').slice(0,2);drag(e,t);e.onclick=()=>{selectedId=t.id;renderMap();detail(t)};l.appendChild(e)})}
function renderTable(q=''){$('#tagTable').innerHTML=tags.filter(t=>(t.name+t.id).toLowerCase().includes(q.toLowerCase())).map(t=>`<tr><td><b>${t.name}</b></td><td>${t.id}</td><td><span class="pill ${t.type}">${t.type==='family'?'Gia đình':'Khách'}</span></td><td>${t.zone}</td><td class="battery-text ${t.battery<20?'low':''}">${t.battery}%</td><td><span class="pill ${t.status}">${t.status==='online'?'Online':'Offline'}</span></td><td><button class="link-btn" onclick="focusTag('${t.id}')">Xem</button></td></tr>`).join('')}
window.focusTag=id=>{let t=tags.find(x=>x.id===id);currentFloor=t.floor;selectedId=id;switchView('locator');$$('#floorSwitch button').forEach(b=>b.classList.toggle('active',b.dataset.floor===currentFloor));renderMap();detail(t)};
function renderAlerts(){let a=[];tags.filter(t=>t.battery<20).forEach(t=>a.push([`Pin yếu: ${t.name}`,`Thẻ ${t.id} còn ${t.battery}%.`]));tags.filter(t=>t.status==='offline'&&t.name!=='Chưa giao').forEach(t=>a.push([`Mất tín hiệu: ${t.name}`,`Lần cuối ${t.last}.`]));$('#alertList').innerHTML=a.map(x=>`<div class="alert-item"><div class="badge-icon">!</div><div><b>${x[0]}</b><small>${x[1]}</small></div></div>`).join('')||'<p>Không có cảnh báo.</p>'}
function render(){renderStats();renderMini();renderAttention();renderMap();renderTable($('#tagSearch').value||'');renderAlerts()}$('#floorSwitch').onclick=e=>{if(e.target.dataset.floor){currentFloor=e.target.dataset.floor;$$('#floorSwitch button').forEach(b=>b.classList.toggle('active',b===e.target));renderMap()}};$('#typeFilter').onchange=renderMap;$('#statusFilter').onchange=renderMap;$('#tagSearch').oninput=e=>renderTable(e.target.value);
$('#simulateBtn').onclick=()=>{let a=tags.filter(t=>t.status==='online'&&t.zone!=='Giá thẻ'),t=a[Math.floor(Math.random()*a.length)];t.floor=Math.random()>.5?'ground':'upper';t.x=10+Math.random()*80;t.y=15+Math.random()*70;t.zone=zone(t.floor,t.x,t.y);t.last='Vừa xong';save();render();toast(`${t.name} vừa đến ${t.zone}`)};
const dlg=$('#guestDialog');$('#addGuestBtn').onclick=()=>{let free=tags.filter(t=>t.type==='guest'&&t.name==='Chưa giao');if(!free.length)return toast('Không còn thẻ khách trống');$('#guestTagSelect').innerHTML=free.map(t=>`<option value="${t.id}">${t.id} · ${t.battery}% pin</option>`).join('');dlg.showModal()};$('#confirmGuest').onclick=e=>{e.preventDefault();let n=$('#guestName').value.trim(),t=tags.find(x=>x.id===$('#guestTagSelect').value);if(!n||!t)return;t.name=n;t.status='online';t.zone=$('#guestZone').value;t.floor=t.zone.includes('tầng trên')?'upper':'ground';t.x=55;t.y=55;t.last='Vừa xong';save();dlg.close();render();toast(`Đã giao ${t.id} cho ${n}`)};
let promptEvent;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();promptEvent=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(!promptEvent)return toast('Trên iPad: Chia sẻ → Thêm vào Màn hình chính');promptEvent.prompt();await promptEvent.userChoice;promptEvent=null;$('#installBtn').hidden=true};function online(){$('#connectionBanner').hidden=navigator.onLine}addEventListener('online',online);addEventListener('offline',online);online();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));render();